/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp;

import static bp.HomePage.admin_check;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gayeu
 */
public class BookPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    DefaultTableModel dtm = new DefaultTableModel();

    public BookPage() {
        initComponents();
        this.setLocationRelativeTo(this);
        jTable1.setModel(dtm);
        ComboType.addItem("Educational Book");
        ComboType.addItem("Scientific Book");
        dtm.setColumnIdentifiers(new String[]{"Id", "Name", "Author", "Stock Status", "Book Type"});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        AddBookButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SearchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RequestedText = new javax.swing.JTextField();
        ListButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AuthorTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AvailableButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        NotAvailableButton = new javax.swing.JRadioButton();
        txtFile = new javax.swing.JButton();
        ComboType = new javax.swing.JComboBox();
        HomePage_Button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Page");
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddBookButton.setForeground(new java.awt.Color(0, 153, 153));
        AddBookButton.setText("Add Book");
        AddBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 114, -1));

        RemoveButton.setForeground(new java.awt.Color(0, 153, 153));
        RemoveButton.setText("Remove Book");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 128, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 273, 745, 295));

        SearchButton.setForeground(new java.awt.Color(0, 153, 153));
        SearchButton.setText("Search by Book Name");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, -1));

        jLabel1.setText("Book Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        getContentPane().add(RequestedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 110, -1));

        ListButton.setForeground(new java.awt.Color(0, 153, 153));
        ListButton.setText("List Book");
        ListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 110, -1));

        jLabel2.setBackground(java.awt.Color.lightGray);
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Book İnformation:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel3.setBackground(java.awt.Color.lightGray);
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("ID:");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        idTextField.setBackground(java.awt.Color.lightGray);
        idTextField.setForeground(new java.awt.Color(204, 0, 0));
        idTextField.setBorder(null);
        idTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 230, -1));

        jLabel4.setBackground(java.awt.Color.lightGray);
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Name:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        NameTextField.setBackground(java.awt.Color.lightGray);
        NameTextField.setForeground(new java.awt.Color(204, 0, 0));
        NameTextField.setBorder(null);
        NameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 230, -1));

        jLabel5.setBackground(java.awt.Color.lightGray);
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Author:");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        AuthorTextField.setBackground(java.awt.Color.lightGray);
        AuthorTextField.setForeground(new java.awt.Color(204, 0, 0));
        AuthorTextField.setBorder(null);
        AuthorTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(AuthorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 230, -1));

        jLabel6.setBackground(java.awt.Color.lightGray);
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Book Type:");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        AvailableButton.setBackground(java.awt.Color.lightGray);
        buttonGroup1.add(AvailableButton);
        AvailableButton.setForeground(new java.awt.Color(204, 0, 0));
        AvailableButton.setText(" Available");
        AvailableButton.setBorder(null);
        AvailableButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(AvailableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 100, -1));

        jLabel7.setBackground(java.awt.Color.lightGray);
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Stock Status:");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        NotAvailableButton.setBackground(java.awt.Color.lightGray);
        buttonGroup1.add(NotAvailableButton);
        NotAvailableButton.setForeground(new java.awt.Color(204, 0, 0));
        NotAvailableButton.setText("Not Available");
        NotAvailableButton.setBorder(null);
        NotAvailableButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(NotAvailableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 120, -1));

        txtFile.setForeground(new java.awt.Color(0, 153, 153));
        txtFile.setText("Export to File");
        txtFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileActionPerformed(evt);
            }
        });
        getContentPane().add(txtFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 110, -1));

        ComboType.setToolTipText("");
        ComboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTypeActionPerformed(evt);
            }
        });
        getContentPane().add(ComboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 230, -1));

        HomePage_Button.setForeground(new java.awt.Color(102, 102, 255));
        HomePage_Button.setText("Go to Home Page");
        HomePage_Button.setContentAreaFilled(false);
        HomePage_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomePage_Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomePage_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePage_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HomePage_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, -1));

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Topic:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 230, -1));

        UpdateButton.setForeground(new java.awt.Color(0, 153, 153));
        UpdateButton.setText("Update İnformation");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection con;
    Statement statement;
    ResultSet result;
    PreparedStatement ps;

    private void ListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListButtonActionPerformed
        // dtm.getDataVector().removeAllElements();
        dtm.setRowCount(0);
        jTable1.setVisible(true);
        int sutunSayisi;
        int kontrol = 0;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/db", "gaye", "gaye");
            statement = con.createStatement();
            result = statement.executeQuery("Select * from BOOKINFORMATION");

            sutunSayisi = result.getMetaData().getColumnCount();

            while (result.next()) {
                Object[] veri = new Object[sutunSayisi];
                for (int i = 1; i <= sutunSayisi; i++) {
                    veri[i - 1] = result.getObject(i);
                }
                dtm.addRow(veri);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi");
        }
    }//GEN-LAST:event_ListButtonActionPerformed

    private void AddBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookButtonActionPerformed

        AddBookButton.setBackground(Color.GRAY);
        boolean sec;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/db", "gaye", "gaye");
            ps = con.prepareStatement("INSERT INTO BOOKINFORMATION (BOOKID,NAME,AUTHOR,STOCKSTATUS,BOOKTYPE) VALUES (?,?,?,?,?)");
            String secilen = (String) ComboType.getSelectedItem();
            ps.setInt(1, Integer.parseInt(idTextField.getText()));
            ps.setString(2, NameTextField.getText());
            ps.setString(3, AuthorTextField.getText());
            if (AvailableButton.isSelected()) {
                sec = true;
            } else {
                sec = false;
            }
            ps.setBoolean(4, sec);
            ps.setString(5, secilen);
            ps.executeUpdate();
            if (secilen.equals("Educational Book")) {
                EducationalBook.Educationalbooks.add(NameTextField.getText());
                EducationalBook.topics.add(jTextField1.getText());
            } else if (secilen.equals("Scientific Book")) {
                ScientificBooks.ScientificBooksName.add(NameTextField.getText());
            }
            Book.booksName.add(NameTextField.getText());
            JOptionPane.showMessageDialog(rootPane, "Book insertion is successful");
        } catch (SQLIntegrityConstraintViolationException sqle) {
            JOptionPane.showMessageDialog(null, "Book id must be different");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "There must be at least 1 stock for book additions");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Database is not connection");
        }
    }//GEN-LAST:event_AddBookButtonActionPerformed

    public void Visible() {
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        idTextField.setVisible(false);
        NameTextField.setVisible(false);
        AuthorTextField.setVisible(false);
        AvailableButton.setVisible(false);
        NotAvailableButton.setVisible(false);
    }
    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed

        dtm.getDataVector().removeAllElements();
        String requested = RequestedText.getText();
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/db", "gaye", "gaye");
            statement = con.createStatement();
            result = statement.executeQuery("SELECT * FROM BOOKINFORMATION  WHERE NAME='" + requested + "'");
            while (result.next()) {
                int id = result.getInt("BOOKID");
                String name = result.getString("NAME");
                String writer = result.getString("AUTHOR");
                boolean stock = result.getBoolean("STOCKSTATUS");
                String type = result.getString("BOOKTYPE");
                dtm.addRow(new Object[]{id, name, writer, stock, type});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something is wrong");
        }

    }//GEN-LAST:event_SearchButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed

        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/db", "gaye", "gaye");
            ps = con.prepareStatement("DELETE FROM BOOKINFORMATION  WHERE NAME=?");
            ps.setString(1, NameTextField.getText());
            ps.executeUpdate();

            dtm.getDataVector().removeAllElements();
            jTable1.repaint();
            if (NameTextField.getText() != null) {
                JOptionPane.showMessageDialog(null, "Deleting is successful");
            }
            dtm.getDataVector().removeAllElements();
            jTable1.repaint();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Something is wrong,Please,write the name of the book which is delete");
        }

    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void txtFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileActionPerformed

        boolean kon = false;
        BufferedWriter bufferedWriter = null;

        File file = new File("C:/Users/gayeu/Desktop/book.txt");
        FileWriter fileWriter;

        try {
            fileWriter = new FileWriter(file, true);
            bufferedWriter = new BufferedWriter(fileWriter);
            if (AvailableButton.isSelected()) {
                kon = true;
            }
            bufferedWriter.write("Book İd: " + idTextField.getText() + "  ");
            bufferedWriter.write("Book Name: " + NameTextField.getText() + "  ");
            bufferedWriter.write("Book Writer:" + AuthorTextField.getText() + "  ");
            bufferedWriter.write("Book Available:" + kon + " ");
            bufferedWriter.write("Book Type :" + ComboType.getSelectedItem() + "  ");
            bufferedWriter.newLine();
            bufferedWriter.flush();
            bufferedWriter.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Wrong ");
        }
        int option = JOptionPane.showConfirmDialog(null, "Save successfully,Do you want to read?", "Choose", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            try {

                BufferedReader reader = null;
                reader = new BufferedReader(new FileReader(file));
                String satir = reader.readLine();

                while (satir != null) {
                    JOptionPane.showMessageDialog(rootPane, satir);
                    satir = reader.readLine();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Something wrong");
            }
        }

    }//GEN-LAST:event_txtFileActionPerformed

    private void HomePage_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePage_ButtonActionPerformed
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_HomePage_ButtonActionPerformed

    private void ComboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTypeActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        if (admin_check == true) {
            try {
                con = DriverManager.getConnection("jdbc:derby://localhost:1527/db", "gaye", "gaye");
                ps = con.prepareStatement("UPDATE BOOKINFORMATION SET STOCKSTATUS=? WHERE BOOKID=?");
                boolean kont = false;
                if (AvailableButton.isSelected()) {
                    kont = true;
                }
                ps.setBoolean(1, kont);
                ps.setInt(2, Integer.parseInt(idTextField.getText()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Change ");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Bir hata oluştu");

            }
            dtm.getDataVector().removeAllElements();
            jTable1.repaint();
        } else {
            int option = JOptionPane.showConfirmDialog(null, "Please log in,Do you want to log in?", "Choose", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                new HomePage().setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBookButton;
    private javax.swing.JTextField AuthorTextField;
    private javax.swing.JRadioButton AvailableButton;
    static javax.swing.JComboBox ComboType;
    private javax.swing.JButton HomePage_Button;
    private javax.swing.JButton ListButton;
    static javax.swing.JTextField NameTextField;
    private javax.swing.JRadioButton NotAvailableButton;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JTextField RequestedText;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton txtFile;
    // End of variables declaration//GEN-END:variables
}
