/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author gayeu
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        this.setLocationRelativeTo(this);
        Hidden();
        Hidd();
        Connect();
        admin_pass_label.setVisible(false);
        jLabel3.setVisible(false);
        AdminButton.setVisible(false);
        UserButton.setVisible(false);
        addpass_button.setVisible(false);
        jLabel4.setVisible(false);

    }
    static boolean admin_check = false;
    static String admin_pass;

    public static void RandomPassword() {
        int[] dizi = new int[4];
        for (int i = 0; i < 4; i++) {
            Random r = new Random();
            int a = r.nextInt(10);
            dizi[i] = a;
        }

        admin_pass = (dizi[0] + "" + dizi[1] + "" + dizi[2] + "" + dizi[3]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        usernametext = new javax.swing.JTextField();
        PasswordText = new javax.swing.JPasswordField();
        Login_Button = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        Label = new javax.swing.JLabel();
        CompleteButton = new javax.swing.JButton();
        Search_Button = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        SelectedBook = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AdminButton = new javax.swing.JRadioButton();
        UserButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        admin_pass_label = new javax.swing.JLabel();
        check_admin = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        addpass_button = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        ScientificList = new javax.swing.JMenuItem();
        EducationalList = new javax.swing.JMenuItem();
        BookPage_Menu = new javax.swing.JMenu();
        Register_Menu = new javax.swing.JMenu();
        Search_Menu = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenuItem1.setText("jMenuItem1");

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 153, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        UserNameLabel.setForeground(new java.awt.Color(255, 102, 0));
        UserNameLabel.setText("User Name:");

        PasswordLabel.setForeground(new java.awt.Color(255, 102, 0));
        PasswordLabel.setText("Password:");

        Login_Button.setForeground(new java.awt.Color(0, 102, 102));
        Login_Button.setText("Login");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });

        NameLabel.setForeground(new java.awt.Color(255, 102, 0));
        NameLabel.setText("Name and Surname:");

        Label.setForeground(new java.awt.Color(255, 102, 0));
        Label.setText("Book Name:");

        CompleteButton.setForeground(new java.awt.Color(0, 102, 102));
        CompleteButton.setText("Complete Registration");
        CompleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteButtonActionPerformed(evt);
            }
        });

        Search_Button.setForeground(new java.awt.Color(0, 102, 102));
        Search_Button.setText("Book Search by BookName");
        Search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ButtonActionPerformed(evt);
            }
        });

        label.setForeground(new java.awt.Color(255, 102, 0));
        label.setText("Name:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 102, 0));
        jRadioButton1.setText("Educational Book List");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 102, 0));
        jRadioButton2.setText("Scientific Book List");

        SelectedBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectedBookActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bp/books.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AdminButton.setForeground(new java.awt.Color(255, 102, 102));
        AdminButton.setText("Admin ");

        UserButton.setForeground(new java.awt.Color(255, 102, 102));
        UserButton.setText("User");

        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Admin Password:");

        check_admin.setText("Are you an admin? ");
        check_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_adminMouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Admin Pass:");

        Menu.setForeground(new java.awt.Color(255, 51, 204));
        Menu.setText("Book List");

        ScientificList.setText("Scientific Book List");
        ScientificList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScientificListActionPerformed(evt);
            }
        });
        Menu.add(ScientificList);

        EducationalList.setText("Educational Book List");
        EducationalList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EducationalListActionPerformed(evt);
            }
        });
        Menu.add(EducationalList);

        jMenuBar1.add(Menu);

        BookPage_Menu.setForeground(new java.awt.Color(255, 51, 153));
        BookPage_Menu.setText("Book Page ");
        BookPage_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookPage_MenuMouseClicked(evt);
            }
        });
        BookPage_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookPage_MenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(BookPage_Menu);

        Register_Menu.setForeground(new java.awt.Color(255, 51, 153));
        Register_Menu.setText("Register");
        Register_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Register_MenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(Register_Menu);

        Search_Menu.setForeground(new java.awt.Color(255, 51, 102));
        Search_Menu.setText("Book Search");
        Search_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_MenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(Search_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(UserNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(PasswordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PasswordText)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addpass_button, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Search_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(check_admin))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CompleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(AdminButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(admin_pass_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SelectedBook, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 14, Short.MAX_VALUE)))
                        .addGap(63, 63, 63)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_admin)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserNameLabel))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasswordLabel)
                            .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Login_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(addpass_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLabel)
                            .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_Button)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label)
                    .addComponent(SelectedBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminButton)
                    .addComponent(UserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admin_pass_label, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CompleteButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void Hidden() {
        NameLabel.setVisible(false);
        nametext.setVisible(false);
        Label.setVisible(false);
        CompleteButton.setVisible(false);
        SelectedBook.setVisible(false);
    }

    public void Open() {
        NameLabel.setVisible(true);
        nametext.setVisible(true);
        Label.setVisible(true);
        CompleteButton.setVisible(true);
        SelectedBook.setVisible(true);

    }

    public static void Connect() {
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/db", "gaye", "gaye");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("Select name from bookınformation where STOCKSTATUS=true");
            while (rs.next()) {
                String name = rs.getString("name");
                SelectedBook.addItem(name);
            }

        } catch (Exception e) {
        }
    }

    Connection con;
    Statement statement;
    ResultSet result;
    PreparedStatement ps;

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        if (check_admin.isSelected()==true) {
            admin_check = true;
            addpass_button.setVisible(true);
            jLabel4.setVisible(true);
            try {
                con = DriverManager.getConnection("jdbc:derby://localhost:1527/db", "gaye", "gaye");
                String userName = usernametext.getText();
                String password = PasswordText.getText();
                String admin_pas = addpass_button.getText();
                statement = con.createStatement();
                result = statement.executeQuery("SELECT USERNAME,PASSWORD,ADMINPASS FROM USERS");
                while (result.next()) {
                    if (result.getString("USERNAME").equals(userName) && result.getString("PASSWORD").equals(password) && result.getString("ADMINPASS").equals(admin_pas) && admin_pas != null && userName != null && password != null) {
                        JOptionPane.showMessageDialog(rootPane, "Log in succesfully,welcome to application");
                        new BookPage().setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Wrong user name or password");
                    }
                    break;
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Database is not connection");
            }
        } else {
            try {
                con = DriverManager.getConnection("jdbc:derby://localhost:1527/db", "gaye", "gaye");
                String userName = usernametext.getText();
                String password = PasswordText.getText();
                statement = con.createStatement();
                result = statement.executeQuery("SELECT USERNAME,PASSWORD FROM USERS");
                while (result.next()) {
                    if (result.getString("USERNAME").equals(userName) && result.getString("PASSWORD").equals(password) && userName != null && password != null) {
                        JOptionPane.showMessageDialog(rootPane, "Log in succesfully,welcome to application");
                        new BookPage().setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Wrong user name or password");
                    }
                    break;
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Database is not connection");
            }
        }
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void CompleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteButtonActionPerformed
        boolean admin = false;

        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/db", "gaye", "gaye");
            ps = con.prepareStatement("INSERT INTO USERS (NAME,USERNAME,PASSWORD,BOOKNAME,ADMIN,ADMINPASS) VALUES (?,?,?,?,?,?)");
            if (AdminButton.isSelected()) {
                RandomPassword();
                admin = true;
                admin_pass_label.setVisible(true);
                jLabel3.setVisible(true);
                admin_pass_label.setText(admin_pass);
            } else if (UserButton.isSelected()) {
                admin = false;
                admin_pass = null;
            }
            ps.setString(1, nametext.getText());
            ps.setString(2, usernametext.getText());
            ps.setString(3, PasswordText.getText());
            ps.setString(4, (String) SelectedBook.getSelectedItem());
            ps.setBoolean(5, admin);
            ps.setString(6, admin_pass);
            if (usernametext.getText() == null || PasswordText.getText() == null) {
                JOptionPane.showMessageDialog(rootPane, "Please write all the information");
            }
            ps.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "Record created is successful");
            nametext.setVisible(false);
            NameLabel.setVisible(false);
            Label.setVisible(false);
            CompleteButton.setVisible(false);
            Login_Button.setVisible(true);
            AdminButton.setVisible(false);
            UserButton.setVisible(false);
            SelectedBook.setVisible(false);
            jLabel3.setVisible(false);
            admin_pass_label.setVisible(false);
            ///guncelleme
            try {
                boolean kont = false;
                con = DriverManager.getConnection("jdbc:derby://localhost:1527/db", "gaye", "gaye");
                ps = con.prepareStatement("UPDATE BOOKINFORMATION SET STOCKSTATUS=? WHERE NAME=?");
                ps.setBoolean(1, kont);
                ps.setString(2, (String) SelectedBook.getSelectedItem());

                ps.executeUpdate();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Bir hata oluştu");

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Database is not connection");
        }
    }//GEN-LAST:event_CompleteButtonActionPerformed

    private void EducationalListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EducationalListActionPerformed
        new EducationalBook(null, null, 0, 0, true, null).ListBook();
    }//GEN-LAST:event_EducationalListActionPerformed

    private void ScientificListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScientificListActionPerformed
        new ScientificBooks(null, null, 0, 0, true).ListBook();
    }//GEN-LAST:event_ScientificListActionPerformed

    private void BookPage_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookPage_MenuActionPerformed
        // new NewJFrame().setVisible(true);
    }//GEN-LAST:event_BookPage_MenuActionPerformed

    private void BookPage_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookPage_MenuMouseClicked
        new BookPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_BookPage_MenuMouseClicked

    private void Register_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_MenuMouseClicked
        Open();
        Login_Button.setVisible(false);
        check_admin.setVisible(false);
        AdminButton.setVisible(true);
        UserButton.setVisible(true);
    }//GEN-LAST:event_Register_MenuMouseClicked

    private void Search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ButtonActionPerformed
        if (jRadioButton1.isSelected() == false && jRadioButton2.isSelected() == false) {
            new EducationalBook(null, null, 0, 0, true, null).BookSearch(jTextField1.getText());
        } else if (jRadioButton1.isSelected() == true || jRadioButton2.isSelected() == true) {
            if (jRadioButton1.isSelected() == true) {
                new EducationalBook(null, null, 0, 0, true, null).BookSearch(jTextField1.getText(), EducationalBook.Educationalbooks);
            } else {
                new EducationalBook(null, null, 0, 0, true, null).BookSearch(jTextField1.getText(), ScientificBooks.ScientificBooksName);
            }
        }
    }//GEN-LAST:event_Search_ButtonActionPerformed
    public void Hidd() {
        jTextField1.setVisible(false);
        label.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        Search_Button.setVisible(false);
    }
    private void Search_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_MenuMouseClicked
        jTextField1.setVisible(true);
        label.setVisible(true);
        jRadioButton1.setVisible(true);
        jRadioButton2.setVisible(true);
        Search_Button.setVisible(true);

    }//GEN-LAST:event_Search_MenuMouseClicked

    private void SelectedBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectedBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectedBookActionPerformed

    private void check_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_adminMouseClicked
        if (check_admin.isSelected()) {
            addpass_button.setVisible(true);
            jLabel4.setVisible(true);
        } else {
            addpass_button.setVisible(false);
            jLabel4.setVisible(false);
        }
    }//GEN-LAST:event_check_adminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AdminButton;
    private javax.swing.JMenu BookPage_Menu;
    private javax.swing.JButton CompleteButton;
    private javax.swing.JMenuItem EducationalList;
    private javax.swing.JLabel Label;
    private javax.swing.JButton Login_Button;
    private javax.swing.JMenu Menu;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JMenu Register_Menu;
    private javax.swing.JMenuItem ScientificList;
    private javax.swing.JButton Search_Button;
    private javax.swing.JMenu Search_Menu;
    static javax.swing.JComboBox SelectedBook;
    private javax.swing.JRadioButton UserButton;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField addpass_button;
    private javax.swing.JLabel admin_pass_label;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox check_admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label;
    private javax.swing.JTextField nametext;
    private javax.swing.JTextField usernametext;
    // End of variables declaration//GEN-END:variables
}
